# Generated by Django 4.0.4 on 2022-05-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.categorie'),
        ),
    ]
