# Generated by Django 4.0.4 on 2022-05-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.categorie'),
        ),
    ]
